### ISSUE TITLE
Website is down

### ISSUE THREAD

**Issue by Duckle29** [sivel/ansible-template-ui#2]
Trying to load the sample I get the following:

![](https://i.imgur.com/bQYkpRB.png)

`Error! timeout: unrecognized option: t BusyBox v1.30.1 (2019-06-12 17:51:55 UTC) multi-call binary. Usage: timeout [-s SIG] SECS PROG ARGS Runs PROG. Sends SIG to it if it is not gone in SECS seconds. Default SIG: TERM.`

**Comment by Lin-Buo-Ren** [comment]
Seems to be fixed now.
